# Generated by Django 3.0.6 on 2021-04-13 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(blank=True, upload_to='plants')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64)),
                ('building_number', models.CharField(max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Oddam'), (2, 'Chcę')])),
                ('amount', models.SmallIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('plant', models.ManyToManyField(to='plantswap.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WATER', 'Podlewanie'), ('FERTILIZE', 'Nawożenie'), ('REPOT', 'Przesadzenie'), ('PRUNE', 'Przycięcie'), ('MIST', 'Zraszanie'), ('ROTATE', 'Odwrócenie')], default='WATER', max_length=9)),
                ('previous_care_day', models.DateField()),
                ('cycle', models.SmallIntegerField(default=7)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantswap.Plant')),
            ],
        ),
    ]
