# Generated by Django 3.0.6 on 2021-04-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0002_auto_20210413_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
