# Generated by Django 3.0.6 on 2021-04-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0005_auto_20210415_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='status',
            field=models.IntegerField(choices=[(1, 'Oddam'), (2, 'Chcę')], default=1),
            preserve_default=False,
        ),
    ]
