# Generated by Django 3.0.6 on 2021-04-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0006_plant_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantTransaction',
            new_name='TransactionPlant',
        ),
        migrations.AddField(
            model_name='plant',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
