# Generated by Django 3.0.6 on 2021-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0007_auto_20210416_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='ordered',
            new_name='finished',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='quantity',
        ),
        migrations.AddField(
            model_name='transactionplant',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
