# Generated by Django 3.0.6 on 2021-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0009_auto_20210416_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(default='test description'),
            preserve_default=False,
        ),
    ]
