# Generated by Django 3.0.6 on 2021-04-16 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantswap', '0011_auto_20210416_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedplant',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wantedplant',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
