# Generated by Django 3.0.6 on 2021-04-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0013_auto_20210417_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='wanted_plant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plantswap.WantedPlant'),
            preserve_default=False,
        ),
    ]
