# Generated by Django 3.0.6 on 2021-04-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0014_comment_wanted_plant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='wantedplant',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='wantedplant',
            name='quantity',
        ),
        migrations.AddField(
            model_name='transaction',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='plantswap.Comment'),
        ),
    ]
