# Generated by Django 3.0.6 on 2021-04-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0015_auto_20210420_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='messages',
            field=models.ManyToManyField(to='plantswap.Comment'),
        ),
    ]
