# Generated by Django 3.0.6 on 2021-04-20 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantswap', '0016_auto_20210420_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WantedPlant',
            new_name='Match',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='wanted_plant',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='created_at',
            new_name='added',
        ),
    ]
