# Generated by Django 3.0.6 on 2021-04-21 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0019_auto_20210421_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='next_care_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
