# Generated by Django 3.0.6 on 2021-05-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0022_auto_20210426_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.IntegerField(choices=[]),
        ),
    ]
