# Generated by Django 3.0.6 on 2021-05-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0023_auto_20210501_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.IntegerField(choices=[(1, 'Oddam'), (2, 'Chcę'), (3, 'Posiadam'), (4, 'Przekazana')]),
        ),
    ]
