# Generated by Django 3.0.6 on 2021-05-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0024_auto_20210501_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.IntegerField(choices=[(1, 'Oddam'), (2, 'Chcę')]),
        ),
    ]
