# Generated by Django 3.0.6 on 2021-05-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0026_auto_20210501_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='plant',
            new_name='match',
        ),
    ]
