# Generated by Django 3.0.6 on 2021-05-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0029_auto_20210501_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='match',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='match',
        ),
        migrations.AddField(
            model_name='message',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='plantswap.Plant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plant',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='plantswap.Plant'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
