# Generated by Django 3.0.6 on 2021-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0030_auto_20210501_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='finished',
            new_name='is_finished',
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
