# Generated by Django 3.0.6 on 2021-05-05 17:54

from django.db import migrations, models
import plantswap.validators


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0031_auto_20210502_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['next_care_day']},
        ),
        migrations.AlterField(
            model_name='reminder',
            name='previous_care_day',
            field=models.DateField(validators=[plantswap.validators.validate_date]),
        ),
    ]
