# Generated by Django 3.0.14 on 2021-05-18 18:56

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantswap', '0032_auto_20210505_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
