# Generated by Django 3.0.14 on 2021-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20210514_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Warszawa', max_length=32),
        ),
    ]
